# Generated by Django 4.0.6 on 2022-08-04 09:43

from django.conf import settings
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('avatar', '250x250', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subs',
            field=models.ManyToManyField(blank=True, default=None, related_name='my_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='subscriptions'),
        ),
    ]
