# Generated by Django 4.0.6 on 2022-08-04 09:57

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_cropping_alter_profile_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=image_cropping.fields.ImageCropField(blank=True, default='img/avatars/avatar.png', upload_to='img/avatars/'),
        ),
    ]
